2024-12-08 22:19:50,108 INFO    MainThread:36913 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-08 22:19:50,108 INFO    MainThread:36913 [wandb_setup.py:_flush():68] Configure stats pid to 36913
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_setup.py:_flush():68] Loading settings from /Users/Nadia/.config/wandb/settings
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_setup.py:_flush():68] Loading settings from /Users/Nadia/Downloads/my_ml_service/wandb/settings
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_init.py:_log_setup():528] Logging user logs to /Users/Nadia/Downloads/my_ml_service/wandb/run-20241208_221950-i75syjze/logs/debug.log
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_init.py:_log_setup():529] Logging internal logs to /Users/Nadia/Downloads/my_ml_service/wandb/run-20241208_221950-i75syjze/logs/debug-internal.log
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_init.py:init():639] calling init triggers
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_init.py:init():688] starting backend
2024-12-08 22:19:50,109 INFO    MainThread:36913 [wandb_init.py:init():692] sending inform_init request
2024-12-08 22:19:50,169 INFO    MainThread:36913 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-12-08 22:19:50,170 INFO    MainThread:36913 [wandb_init.py:init():705] backend started and connected
2024-12-08 22:19:50,175 INFO    MainThread:36913 [wandb_init.py:init():798] updated telemetry
2024-12-08 22:19:50,176 INFO    MainThread:36913 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-08 22:19:50,178 WARNING MsgRouterThr:36913 [router.py:message_loop():75] message_loop has been closed
2024-12-08 22:19:55,199 ERROR   MainThread:36913 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/Users/Nadia/Downloads/my_ml_service/my_ml/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/Nadia/Downloads/my_ml_service/my_ml/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Nadia/Downloads/my_ml_service/my_ml/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
